apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubernetes-module-exercise 
  labels:
    purpose: read-write-to-file
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: time-printer
    spec:
      containers:
      - name: time-writer
        image: alpine:3.6
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date) >> /time-space/time ; sleep 5; done"]
        volumeMounts:
        - mountPath: /time-space
          name: cache-volume
      - name: time-reader
        image: alpine:3.6
        command: ["/bin/sh"]
        args: ["-c", "while true; do tail -1 time-space/time ; sleep 5; done"]
        volumeMounts:
        - mountPath: /time-space
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}